### ISSUE TITLE
Allow setting of grid-items without declaring position

### ISSUE THREAD

**Issue by martindelima** [JohnAlbin/zen-grids#35]
Just a question, could there be a way to perhaps only include the columns spanned by an item and just floating it, instead of having to always declare from which column it starts? list items for navigation, for example, are a little difficult to handle with this.

**Comment by JohnAlbin** [comment]
> could there be a way to perhaps only include the columns spanned by an item and just floating it, instead of having to always declare from which column it starts

There are lots of grid systems that allow that. They also require the use of push and pull classes in order to re-arrange items in the row. I find those push and pull classes annoying and confusing to understand.
