### ISSUE TITLE
Can't right-align content, please help.

### ISSUE THREAD

**Issue by kakubei** [JohnAlbin/zen-grids#59]
I really lke Zen Grids, thanks for creating this. But I have a problem I can't quite figure out. I have 4 elements that I want to arrange, the first 2 on the left, the other 2 on the right. They are divided in pairs inside divs. But I also need them to never overlap (any of the items), even when you shrink the window.

In Zen grids I have:

    .left-div { @include zen-grid-item(3,1) }
    .right-div { @include zen-grid-item(3,4) }

Which works fine as far as overlapping goes, but the right edge of the right-div element is not aligned right, it is aligned left. See image below

![right align](https://f.cloud.github.com/assets/1465323/2356755/374d5bd4-a5f2-11e3-9048-26941da32fc1.png)

This is true, even if I do:

    .left-div { @include zen-grid-item(3,1) }
    .right-div { @include zen-grid-item(3,1, right) }

I simply cannot get that right element to align to the right. 

Any help would be greatly appreciated. And thanks again.

**Comment by JohnAlbin** [comment]
Add the text-align CSS property.
