### ISSUE TITLE
Control global grid variables and breakpoint from a single mixin

### ISSUE THREAD

**Issue by DannyJoris** [JohnAlbin/zen-grids#66]
With Zen grids 2 I’m trying to set the column count once for all viewports, but this doesn’t seem to work. When I include the $zen-columns variable right before the zen-grid-item(), it does, but I’d rather not repeat this variable every time I use specify a breakpoint on an element. I'm using breakpoint, but I also tried with normal @media queries. Maybe it's because it's not applied to any css selector? How should I approach this?

```
// Zen grids
$zen-gutter-method: margin;
$zen-columns: 4 !global;
$zen-gutters: 1.7% !global;
@include breakpoint($narrow) {
  $zen-columns: 6 !global;
}
@include breakpoint($tablet) {
  $zen-columns: 8 !global;
}
@include breakpoint($computer) {
  $zen-columns: 12 !global;
}
@include breakpoint($wide) {
  $zen-columns: 12 !global;
}
```

**Comment by JohnAlbin** [comment]
I've got this working now in a new layout module.
