### ISSUE TITLE
Compass v1 seems to break zen grids

### ISSUE THREAD

**Issue by 4ll4n** [JohnAlbin/zen-grids#68]
Could be due to dropping legacy support variables but I'm unsure. 
Upshot is zen-grid-item() doesn't seem to do its job anymore.

Looking into it, it looks like resetting $zen-column-count inside selectors no longer works

**Comment by shayank** [comment]
zen-column-count seems work with !global.
https://www.drupal.org/node/2346291#comment-9475791

**Comment by JohnAlbin** [comment]
Use Zen Grids 2.x instead.
