### ISSUE TITLE
zen-clear seems to not work with IE7 / IE6 

### ISSUE THREAD

**Issue by El-Muerto** [JohnAlbin/zen-grids#73]
I tried the example 2 in the documentation (http://zengrids.com/help/#example-2) and it is like the zen-clear is not working. I am not sure if I am missing something.

HTML:
<pre>
&lt;div class="example-container"&gt;
  &lt;div class="block-a"&gt;
    &lt;div class="content"&gt;
      &lt;p&gt;Lorem ipsum&lt;/p&gt;
    &lt;/div&gt;
  &lt;/div&gt;
  &lt;div class="block-b"&gt;
    &lt;div class="content"&gt;
      &lt;p&gt;Lorem ipsum&lt;/p&gt;
    &lt;/div&gt;
  &lt;/div&gt;
  &lt;div class="block-c"&gt;
    &lt;div class="content"&gt;
      &lt;p&gt;Lorem ipsum&lt;/p&gt;
    &lt;/div&gt;
  &lt;/div&gt;
  &lt;div class="block-d"&gt;
    &lt;div class="content"&gt;
      &lt;p&gt;Lorem ipsum&lt;/p&gt;
    &lt;/div&gt;
  &lt;/div&gt;
&lt;/div&gt;
</pre>

SASS:
<pre>
@import "zen";

$zen-grid-width: 984px;
$zen-column-count: 3; // Set the total number of columns in the grid.
$zen-gutter-width: 10px;

$box-sizing-polyfill-path: "/sites/all/themes/sitename/htc/boxsizing.htc";
$legacy-support-for-ie6: true;
$legacy-support-for-ie7: true;
$legacy-support-for-ie8: true;

.example-container {
  width: $zen-grid-width;
  margin-left: auto;
  margin-right: auto;
  @include zen-grid-container; // Apply this mixin to the container.
}

.block-a {
  @include zen-grid-item(2, 1);
}

.block-b {
  @include zen-grid-item(1, 1, right);
}

.block-c {
  @include zen-clear(right);
  @include zen-grid-item(1, 1, right);
}

.block-d {
  @include zen-clear(both);
  @include zen-grid-item(3, 1);
}
</pre>

**Comment by JohnAlbin** [comment]
zen-clear() has been replaces with zen-new-row().
