### ISSUE TITLE
Setting environment documentation

### ISSUE THREAD

**Issue by macmladen** [JohnAlbin/zen-grids#74]
Zen Grids is advertised as standalone grid system like Susy, Singularity or any other.

While that is possible and true, and basic usage provides some information (both here and on next.zengrids.com) it is not as clear how to set up environment and get the most of what Zen Grids can offer.

For instance, looking at source and from experience with `aurora` I tried and succeeded to make sample project by issuing commands:

` compass create myzen -r zen-grids`

and

`compass create myzen2 -r zen-grids --using zen-grids/project`

They produce folder structure with some `scss` that gives a good start and also provide `config.rb` _free of charge_.

I think this should be documented.

Also it would be nice to have documentation on some best practices on setting environment like it is suggested for Drupal Zen theme with all things like `rvm`, `bundler`, `bower`, `gulp` and other niceties that make frontender feel at home.

**Comment by JohnAlbin** [comment]
FYI, I removed the ability to `compass create myzen2 -r zen-grids --using zen-grids/project` because it was hard to maintain and I wasn't even sure if anyone was using it.
