### ISSUE TITLE
Second column margin-left miscalculation(?) on a 2 column grid

### ISSUE THREAD

**Issue by ssirois** [JohnAlbin/zen-grids#75]
On a two column grid, the second column margin-left is set to 100% but should be set to 50% to my understanding. This is reproducible in version 1.4, but also at the head of the repository.

* See the reproducible erroneous behavior code here: https://gist.github.com/ssirois/dcee61ac0bed9e7eb94e/8d0b08a80d17cb92d6af9a2874b576bf78fb3505
* See the same code, but with a fixed margin-left here: https://gist.github.com/ssirois/dcee61ac0bed9e7eb94e

If the issue is identified as real and not a misunderstanding on my part, I can implement an accepted solution that would have been discussed here and send a pull requests. I am usually free to hack on libre/free projects on Mondays and Fridays.

**Comment by JohnAlbin** [comment]
In recent versions of Sass, when you do this inside a CSS ruleset:
```
.ex {
  $zen-column-count: 2;
  $zen-gutter-width: 0px;
  @include some-mixin();
}
```

You are creating local variables that the some-mixin() cannot see.

You need to use the `!global` flag to set those variables.
