### ISSUE TITLE
Which is the substitute of zen-nested-container on zg v2

### ISSUE THREAD

**Issue by rpayanm** [JohnAlbin/zen-grids#79]
Hello,

I was used in my project, zg v1, the mixin zen-nested-container, but when use this on a other project, zg v2, I got this error:
```
Undefined mixin 'zen-nested-container'.
```

**Comment by JohnAlbin** [comment]
The docs have been fully updated. http://zengrids.com

You need to use the `zen-grid-container(grid-item)` or `zen-grid-container(flow)`, depending on how the nested container is actually nested. See http://zengrids.com/help/section-grids.html#kssref-grids-zen-grid-container
